### ISSUE TITLE
"Can't find '__main__' module in 'themer'"

### ISSUE THREAD

**Issue by ScottKaye** [s-ol/themer#13]
I have both Python 2.7 and Python 3 installed on 64-bit Linux Mint running in Virtualbox.  Unfortunately, I have never written a line of Python in my life, and am running into this error when I run `python3 themer generate themename ~/wallpaper.jpg`:

`/usr/bin/python3: can't find '__main__' module in 'themer'`

If I run the command without `python3`, I get the same error as [Issue 6](https://github.com/S0lll0s/themer/issues/6):

```
Traceback (most recent call last):
  File "/usr/local/bin/themer", line 5, in <module>
    pkg_resources.run_script('Themer==1.0', 'themer')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1400, in run_script
    script_code = compile(script_text,script_filename,'exec')
  File "/usr/local/lib/python2.7/dist-packages/Themer-1.0-py2.7.egg/EGG-INFO/scripts/themer", line 195
    print(msg,file=sys.stderr)
                  ^
SyntaxError: invalid syntax
```

I hope this is just a noob mistake on my end!

**Comment by s-ol** [comment]
You cannot run it with python3 prefix like that, either run

```
 python3 `which themer` generate
```

Or modify themer (in /usr/bin) to change the shebang:

```
 #!/use/bin/env python3
```

So that the python3 interpreter is used by default
