### ISSUE TITLE
setup.py tries to install to root instead of fake-root, fails on Arch

### ISSUE THREAD

**Issue by phijor** [s-ol/themer#16]
I tried to install `themer` from the AUR, but it always failed with:

```
error: could not create directory '/usr/share/themer'
```

After a bit of digging, I found out that `setup.py` tries to install to root, which one does not have the permissions to when building from AUR. Instead, the package should try to install to the current working directory, aka the fake-root `--root="${pkgdir}"`.

I forked `themer` and removed the prefix `/` and it now happily builds with `makepkg`.

**Comment by s-ol** [comment]
@phijor oh and by the way, if you end up writing any useful plugins, let me know so I can merge them in aswell.

**Comment by phijor** [comment]
@S0lll0s yeah, I'll look into that when I have the time. I'm glad I could contribute to the project, it feels good to know that I fixed something.

Btw: Look at the AUR-page for `themer`. It seem like a package is missing from the dependency-array, though I'm not quite sure wether it's just an error on my part or not.

**Comment by s-ol** [comment]
Oh, right! I added python-requests to the package and removed the verson-dependency on python3 (the same commit that introduced requests enabled python2 compatibility).

**Comment by s-ol** [comment]
During testing just now I found that without the slashes it actually does _not_ install with `sudo setup.py install`. It instead creates the directory `usr` inside the source repo. I accidentally reverted back to the original version in 948b3fac29938073351aff6103451fff26bf9db9; not sure how to handle this...
