### ISSUE TITLE
Wallfix Activator not found

### ISSUE THREAD

**Issue by jedStevens** [s-ol/themer#23]
On a new install, generating a theme fails when it cant find any activator.

```
themer generate default ~/Downloads/wallpaper.png 
Traceback (most recent call last):
  File "/usr/bin/themer", line 266, in <module>
    load_plugins(config)
  File "/usr/bin/themer", line 191, in load_plugins
    plugins[kind].append(imp(name))
  File "/usr/bin/themer", line 184, in imp
    mod = __import__('.'.join(name.split('.')[:-1]))
ImportError: No module named themer.activators.wallfix
```

**Comment by s-ol** [comment]
Are you running multiple versions of python? It could be that the script is getting executed with a different version of python than the module was installed to maybe. I'll take a look tomorrow and see if it is some obvious flaw I committed recently...

**Comment by jedStevens** [comment]
I am currently running the latest versions of python2 and python from the Arch packages.
I've also changed `#!/usr/bin/python` to `#!/usr/bin/python2` with no luck.

**Comment by s-ol** [comment]
Hm, a few more questions:
- What do you get when you enter `import themer.activators.wallfix` in an interactive python shell (of both versions)?
- How did you install `themer`?
- Can you find `themer/activators/wallfix.py` somewhere in your python site-packages (for example in `/usr/lib/python3.4/site-packages/themer/activators/wallfix.py` on my machine)

**Comment by jedStevens** [comment]
- importing `themer.activators.wallfix` only imports in `python` and not `python2`
- I installed themer using the command `yaourt themer`
- The contents of my `/usr/lib/python3.4/site-packages/themer/activators`:
  - `acyl.py` `i3.py` `__init__.py`  `__pycache__/` `wallfix.py`
- `python2` doesn't have `themer/` in its respective `site-packages/`

**Comment by s-ol** [comment]
all of this is exactly as it should be... are you **sure** that your themer binary is running as python3? maybe try changing the shebang to `python3`?

**EDIT:** also I suppose by `yaourt themer` you mean at least `yaourt python-themer-git`

**Comment by s-ol** [comment]
Wait, I think I might have found something. I'll look further tomorrow....

**Comment by s-ol** [comment]
Hm no, I had a similar error but it turned out to be a difference in my personal configuration file.

I cleaned my installation with a sane config file and reinstalled themer via the AUR and everything is working fine. Can you maybe show your `config.yaml` and the directory listing under `.config/themer`?

**Comment by nineluj** [comment]
I get the same error running the script under python2 after having installed all the dependencies but I get the following when running it under /usr/bin/python3

themer generate rocketcolors ~/.wallpapers/rocketcolors.jpg                              [12:54:13]
Traceback (most recent call last):
  File "/usr/bin/themer", line 294, in <module>
    generate(color_file, config, template_dir, theme_name)
  File "/usr/bin/themer", line 145, in generate
    colors = parse.read()
  File "/usr/lib/python3.5/site-packages/themer/parsers/**init**.py", line 162, in read
    color = self.normalize(color, minv=0, maxv=32)
  File "/usr/lib/python3.5/site-packages/themer/parsers/**init**.py", line 153, in normalize
    return self.rgb_to_hex(map(lambda i: i \* 256, rgb))
  File "/usr/lib/python3.5/site-packages/themer/parsers/**init**.py", line 128, in rgb_to_hex
    return '#{}'.format(''.join(('%02x' % p for p in rgb)))
  File "/usr/lib/python3.5/site-packages/themer/parsers/**init**.py", line 128, in <genexpr>
    return '#{}'.format(''.join(('%02x' % p for p in rgb)))
TypeError: %x format: an integer is required, not float

Any idea what could be causing this?

**Comment by shanebrowncs** [comment]
I get this same error with Python 3.5.1 on Arch Linux. I've tried building from source, installing via AUR, and using PIP. Must be something with my individual system.

Traceback (most recent call last):
  File "/usr/bin/themer", line 294, in <module>
    generate(color_file, config, template_dir, theme_name)
  File "/usr/bin/themer", line 145, in generate
    colors = parse.read()
  File "/usr/lib/python3.5/site-packages/themer/parsers/**init**.py", line 162, in read
    color = self.normalize(color, minv=0, maxv=32)
  File "/usr/lib/python3.5/site-packages/themer/parsers/**init**.py", line 153, in normalize
    return self.rgb_to_hex(map(lambda i: i \* 256, rgb))
  File "/usr/lib/python3.5/site-packages/themer/parsers/**init**.py", line 128, in rgb_to_hex
    return '#{}'.format(''.join(('%02x' % p for p in rgb)))
  File "/usr/lib/python3.5/site-packages/themer/parsers/**init**.py", line 128, in <genexpr>
    return '#{}'.format(''.join(('%02x' % p for p in rgb)))
TypeError: %x format: an integer is required, not float

Following the questions posed above:
/usr/lib/python3.5/site-packages/themer/activators/wallfix.py is the path to wallfix.py

I've ensured it is using Python 3 by running the command python3 to execute it.

Under ~/.config/themer the only thing in the directory is a folder called "Templates". Even after attempting theme generation. I'm using i3 so I am just using the default setup shown on the README page.

Any help you can give would be greatly appreciated, thanks.

**Comment by fibonascii** [comment]
Also receiving the same error

  File "/usr/lib/python3.5/site-packages/themer/activators/wallfix.py", line 22, in <module>
    RATIO = float(WIDTH) / HEIGHT
NameError: name 'WIDTH' is not defined

**Comment by s-ol** [comment]
Those errors are 3.5.

**Comment by hashkeks** [comment]
It seems that I have a similiar when not the same error as the people here:
Traceback (most recent call last):
  File "/usr/bin/themer", line 295, in <module>
    load_plugins(config)
  File "/usr/bin/themer", line 218, in load_plugins
    plugins[kind].append(imp(name))
  File "/usr/bin/themer", line 211, in imp
    mod = __import__('.'.join(name.split('.')[:-1]))
  File "/usr/lib/python3.6/site-packages/themer/activators/wallfix.py", line 22, in <module>
    RATIO = float(WIDTH) / HEIGHT
NameError: name 'WIDTH' is not defined

This comes when I try to generate a theme. I installed it via PIP, yaourt and then did a manual installation, but nothing helped. The dependencies are installed too. I'm using the most recent python and python2 arch packages and changing the shebang in /bin/themer form python to python3.6 didn't work. Changing to python2 brought this error: 
Traceback (most recent call last):
  File "/usr/bin/themer", line 19, in <module>
    import yaml
ImportError: No module named yaml
But I think this should be normal with python2, shouldn't it?

**Comment by s-ol** [comment]
the reason you cannot run it with python2 is because you haven't installed the dependencies in python2. 

Can you try adding

    WIDTH = 1440
    HEIGHT = 900

above the try/except block in `themer/activators/wallfix.py`?
