### ISSUE TITLE
Make using multiple template sets more convenient

### ISSUE THREAD

**Issue by s-ol** [s-ol/themer#26]
Ideas:
- remember last used template instead of defaulting to i3
- reorganize themes in subdirectory (`~/.config/themer/themes`) for simpler directory structure (and no reserved names)

**Comment by Kashyap12** [comment]
Hi @s-ol , I am new to open source, would love to contribute

**Comment by s-ol** [comment]
Hey @Kashyap12. After checking your profile, I assume you came here from the `up-for-grabs` site or something similar. Here are a few questions for you:

- do you know what this project is exactly?
- have you managed to set it up and tried using it?

It is not a problem if you were to answer 'no' to either of the questions. The reason I am asking is that the project is right now in a 'weird' state; it is more or less functional and full-featured, but I am not happy with most of it and want to rewrite the bigger part from scratch. This issue is concerned with one of the core parts of the current structure (this doesn't mean it's hard to implement, though), and would likely be completely scrapped for the upcoming rewrite. If you don't mind that you can of course still submit a PR for this and I will merge it if it fits the current standards.

I am also sorry for not moderating these issues and the `up-for-grabs` labels more closely, at the moment #40 would probably be a better place to start, I suggest you take a look. It is less involved with boring, core part of the program and more with the actual user side, smaller, and likely to survive the rewrite and make it into v2.0.

If you like the project and are personally using it or would at least be considering to use it personally, have _some_ python experience or at least some comparable scripting language, I would be even more happy to have someone work on a `themer 2.0`.

**Comment by s-ol** [comment]
Superseded by #51.
