### ISSUE TITLE
Decide on image processing interface and dataflow

### ISSUE THREAD

**Issue by s-ol** [s-ol/themer#27]
For example for projects like [onespaceman/polyfy](/onespaceman/polyfy).

I am not sure how the interface will work, via paths and temporary files or via `PIL Image` object... both have drawbacks.

**Comment by Kaligule** [comment]
To be honest, I don't think it should be themers job to do this.

**Comment by s-ol** [comment]
@Kaligule I didn't mean to implement image processing tools, but to properly define the pipeline and interface for handling wallpapers. I guess the file-abstraction is fine right now, but I want to make the processing in the parsers less weird and magical.
