### ISSUE TITLE
aur pkgbuild install still fails with empty pkgver

### ISSUE THREAD

**Issue by ayushjsh** [s-ol/themer#32]
I could'nt comment on the Aur, but the install via aur still fails with pkgver() is not allowed to be empty.

**Comment by s-ol** [comment]
Very weird, what AUR helper and/or commands are you using? Been working perfectly fine before and after my last update and I even added a dummy pkgver in addition to the dynamic pkgver() function

**Comment by ayushjsh** [comment]
I am using Packer, I just updated everything and tried again to no avail. packer -S python-themer-git still gives me the pkgver is not allowed to be empty error.

**Comment by s-ol** [comment]
Could you maybe try installing python-powerline or python-powerline-git? I based my PKGBUILD on theirs, so that would be a good reference point. I'll try building with packer too when I get home.

**Comment by s-ol** [comment]
@ayushjsh are you sure you are not building from a cached old `PKGBUILD`? just successfully built using latest `packer` without any issues.
