### ISSUE TITLE
Writing a better README

### ISSUE THREAD

**Issue by ghost** [s-ol/themer#33]
need to write a better readme file so that noobs like me could understand.Sorry if I was rude

**Comment by s-ol** [comment]
I'm working on pretty much rewriting themer as a whole at the moment, not sure if it is worth it to overhaul the README. What part exactly do you not understand? Installation, Configuration/Setup or Usage?

**Comment by ghost** [comment]
The configuration part. Just don't understand how it works and I see nothing when I use themer activate.Do I need to set the wallpaper for it to work? And also when i enter the command `themer current` to check the colors I created from a picture, it says `sh:colortheme:command not found`.Thanks for considering to help me!

**Comment by s-ol** [comment]
Well, what window manager or desktop environment are you trying to configure?

You need to have/write a template for whatever you are going to configure and you need to symlink the rendered config file to it's expected location (see ["Integrating themer with your setup"](https://github.com/s-ol/themer#integrating-themer-with-your-setup)).

For `themer current` you need to install `colortheme` (or roll your own script with that name).

**Comment by ghost** [comment]
I have i3 on Arch. I got the script somewhere on the internet and placed it in my `/bin/` folder. It works nicely.But I still don't see how the script works.I tried integarting `.Xresources`and `.config/i3/config` and it still doesn't work. I want to reinstall the script and try again with the instructions you will provide.

**Comment by s-ol** [comment]
What do you mean you did when you say _I tried integarting .Xresourcesand .config/i3/config and it still doesn't work._? If you are using the default templates you need to symlink `.config/themer/current/i3.conf` to it's destination (`.config/i3/config` with current i3, `.i3/config` with older).

Do you even have a `.config/themer`? Do you have a `.config/themer/current`? Does it contain rendered config files? I don't think reinstalling themer will do anything.

**Comment by ghost** [comment]
Sorry for not expalining clearly.I used the command `ln -s ~/.config/themer/current/.Xresources ~/.Xresources` and `~/.config/themer/current/config ~/.config/i3/config`(which is the i3-config file).
I do have a `.config/themer` directory and a `current` folder in it. I copied the config from the `~/.config/i3/config`and `config.yaml` along with `~/.Xresources` to the `~/.config/themer/templates/i3/`. I then issued  a command `themer generate theme-one ~/.(a pic)` and activated it to see nothing changing at all. 

P.S. I am also using i3-style which can use already built theme-files and add them to my config.Will it cause problems to the script?

**Comment by s-ol** [comment]
@harsha003 well, the `templates` folder is supposed to contain _templates_ for config files, not config files. If you just put in a regular config file it get's rendered but nothing in the file will change so you see the same resullt. You need to add template tags that put the colors into the places you want them.

For example, look at the default i3 template:
https://github.com/s-ol/themer/blob/develop/data/default/templates/i3/i3.tpl

```
set $mod Mod4

set $background {{ black }}
set $foreground {{ white }}
set $gray       {{ alt_black }}
set $primary    {{ primary }}
set $secondary  {{ secondary }}
set $tertiary   {{ tertiary }}
set $warning    {{ special }}
...
```

`{{` and `}}` denote a template tag that will be replaced by the color value. the i3 variables defined here are then used further down in the config.

You need to add your own template tags to your config (the one in the templates directory) and make sure that the template name is correct in `config.yaml`.

How do you expect themer and i3-style to work together? They will both change the colorscheme so, at best, one of them will work, depending on how you want to use it. Either i3-style will overwrite the template tags of variables (if you run it over the themer template) or it will unset the colors themer set (if you run it over the rendered config). If you add template tags to the config you updated with i3-style then you undo what i3-style does. I don't see how you could be using both.

**Comment by ghost** [comment]
Oh that's it. I didn't know how it worked. Thank you for bearing with me. Also, I only said I used i3-style and that it worked because it adds it's own colors. But themer didn't work as I had to manually do the `{{ }}` correctly as you did in your templates.

**Comment by ghost** [comment]
Could you tell me when you will have completed the rewrite of themer?

**Comment by s-ol** [comment]
If you 'watch' the repo you will see a few issues being closed and commits coming in.
On Jun 9, 2016 5:15 PM, harsha003 notifications@github.com wrote:Could you tell me when you will have completed the rewrite of themer?

**Comment by ghost** [comment]
Ok. Thanks again.

**Comment by ghost** [comment]
I'm closing it now.
