### ISSUE TITLE
Add jinja filters for color formatting in templates

### ISSUE THREAD

**Issue by useronym** [s-ol/themer#40]
Hi,
it seems that by default, the colors are formatted as `#RRGGBB`. Only information I could find about the syntax for template files were the i3 examples — is it possible to format colors differently? For example, transparency in lemonbar is specified in the color as `#AARRGGBB`. If you want transparency in Termite, you need `rgba(r, g, b, a)`, where r, g, b are 8-bit ints and a is a float. With lemonbar, I can transform to the correct format with bash, but I have no idea how to handle Termite.

**Comment by s-ol** [comment]
You can use the [jinja filters](http://jinja.pocoo.org/docs/dev/templates/#builtin-filters) to transform values in the template.

I suppose it would make sense to add custom filters to extract the R, G, B and A components seperately.

**Comment by useronym** [comment]
Any tips on how would one go about creating such filters?

**Comment by useronym** [comment]
Never mind, decided it would be easier to just give i3 & urxvt a shot.

**Comment by s-ol** [comment]
well the issue is relevant anyway. I'll keep it in mind for themer 2.0 coming soon™
