### ISSUE TITLE
`generate` silently, seemingly randomly fails

### ISSUE THREAD

**Issue by useronym** [s-ol/themer#41]
I must be doing something wrong since no one else seems to be having this issue, but for me, `themer generate [...]` works only occasionally. This seems to be input image-dependent.

For some images, I get a complaint about not using PyPI:
```
Falling back to python kmeans implementation.
            Consider installing 'kmeans' from PyPI for much faster image sampling
Activate now? yN
```
This is the *only* case when `themer generate` actually works. About 5/34 images do this, i.e. actually work.

For others, I just get a nag about activating the theme:
```
Activate now? yN
```
These generate the correct colors in `colors.yaml`, however looking at `wallpaper.png` I always get a piece of abstract art like this:
![wallpaper](https://cloud.githubusercontent.com/assets/4563753/20466560/dce318e2-af75-11e6-9c3c-862027089487.png)
The shapes are always the same, but their colors change depending on the colors in the input image. This is the most usual: 27/34 images induce this behavior.

Still others simply crash:
```
Traceback (most recent call last):
  File "/usr/bin/themer", line 294, in <module>
    generate(color_file, config, template_dir, theme_name)
  File "/usr/bin/themer", line 145, in generate
    colors = parse.read()
  File "/usr/lib/python3.5/site-packages/themer/parsers/__init__.py", line 158, in read
    colors = self.get_dominant_colors()
  File "/usr/lib/python3.5/site-packages/themer/parsers/__init__.py", line 141, in get_dominant_colors
    rgbs = kmeans.kmeans(points, self.k)
  File "/usr/lib/python3.5/site-packages/themer/parsers/__init__.py", line 93, in kmeans
    distance = self.ec_dist(p, clusters[i][1])
  File "/usr/lib/python3.5/site-packages/themer/parsers/__init__.py", line 73, in ec_dist
    sum((a[0][i] - b[0][i]) ** 2 for i in range(3)))
  File "/usr/lib/python3.5/site-packages/themer/parsers/__init__.py", line 73, in <genexpr>
    sum((a[0][i] - b[0][i]) ** 2 for i in range(3)))
TypeError: 'int' object is not subscriptable
```
This is the most rare — about 2/34.

What's going on? I installed themer from AUR:
```
➜  ~ pacman -Qs python-themer
local/python-themer-git v1.6.r0.gfc24e5b-1
```
Any help will be appreciated.

**Comment by useronym** [comment]
Okay, seems like this is fixed in the development branch. Never mind, I guess :)

**Comment by useronym** [comment]
The abstract art is pretty, though :P

**Comment by useronym** [comment]
Ah yeah, also just noticed the closed issue #34. Perhaps it should be back-ported back to master, or at least the AUR package should install the development branch?

**Comment by s-ol** [comment]
@osense i just need to merge into master and push a release. I'll try to do it today or tomorrow.

**Comment by useronym** [comment]
Great!

One more thing, I know this probably isn't the best place to ask, but I don't want to create another issue: Where do the colors `foreground` and `background` come from? They never change in dependence on the wallpaper, but they're not declared in config.yaml, either.

**Comment by s-ol** [comment]
I realeased something today, could you check if it is working properly? I am very unsure if the `setup.py` is working as inteded or broken again/still. Thank's for testing and feedback by the way, I feel like I might maybe finally have the motivation to get 2.0 off the ground again.

**Comment by useronym** [comment]
Well I only use the AUR package, but yeah, everything seems fine.
