### ISSUE TITLE
Light background switcher?

### ISSUE THREAD

**Issue by artur-shaik** [s-ol/themer#42]
As I can see, themer makes dark background themes only. Any chances to do light as well?

**Comment by s-ol** [comment]
it is done [here](https://github.com/s-ol/themer/blob/develop/themer/activators/wallfix.py#L25).

I guess it could be improved but I never did because I don't use these wallpapers myself. How would you want to specify that?

**Comment by artur-shaik** [comment]
I thought it should be done in theme generation code. Maybe just exchange `foreground` and `background`, and reverse `colors` array. For example with command line argument switcher `--light` or `--dark`.
