### ISSUE TITLE
What is the full process for adding a plugin?

### ISSUE THREAD

**Issue by Amar1729** [s-ol/themer#43]
I'm in the middle of writing an iTerm2 parser to generate colorschemes for iTerm2. So far, I've:  
* written a file `iTerm.py` with the appropriate definition and class functions for a `ColorParser`  
* placed it in `~/.config/themer/templates/i3/plugins`
* placed it in `themer`'s `env/lib/python2.7/site-packages/themer/plugins/` directory
* added the line `   - themer.parsers.iTerm` to `config.yaml` under `plugins/parsers`
* written the `iterm2.tpl` file and placed it under `~/.config/themer/templates/i3/` (with the other `.tpl`s)
* added the line `iterm2.tpl: iterm.itermcolors` to `config.yaml` under `files`

Output of `$ themer plugins`:  
```
Enabled activators:
	themer.activators.wallfix.WallfixActivator
	themer.activators.i3.I3Activator
Enabled parsers:
	themer.parsers.SweylaColorParser
	themer.parsers.WallhavenColorParser
	themer.parsers.KmeansColorParser
	themer.parsers.CachedColorParser
	themer.parsers.unsplash.UnsplashColorParser
	themer.ColorParser
	themer.parsers.iTerm
```

However, the output of `$ themer -d generate cm ~/wallpapers/cloudmountain.jpg`:
```
Reading config file: /Users/Amar/.config/themer/templates/i3/config.yaml
xrandr: Failed to get size of gamma for output default
Loaded plugin "themer.activators.wallfix.WallfixActivator"
Loaded plugin "themer.activators.i3.I3Activator"
Loaded plugin "themer.parsers.SweylaColorParser"
Loaded plugin "themer.parsers.WallhavenColorParser"
Loaded plugin "themer.parsers.KmeansColorParser"
Loaded plugin "themer.parsers.CachedColorParser"
Loaded plugin "themer.parsers.unsplash.UnsplashColorParser"
Loaded plugin "themer.ColorParser"
Traceback (most recent call last):
  File "/Users/Amar/Documents/Projects/themer/env/bin/themer", line 268, in <module>
    load_plugins(config)
  File "/Users/Amar/Documents/Projects/themer/env/bin/themer", line 193, in load_plugins
    plugins[kind].append(imp(name))
  File "/Users/Amar/Documents/Projects/themer/env/bin/themer", line 188, in imp
    mod = getattr(mod, n)
AttributeError: 'module' object has no attribute 'iTerm'
```

Note: I am using a `git clone`'d version of `themer` (not from PyPi) and it's running under a virtual environment rather than having been `sudo install`ed.

**Comment by s-ol** [comment]
your module is not going to be under 'themer.parsers', it's imported like any python module. If it is a file called `iTerm.py` with a class called iTermParser in the plugins folder, you can use it as `iTerm.iTermParser`.

Also in case you didn't knowl, you don't need a Parser to be able to render to Iterm2 colors.

**Comment by Amar1729** [comment]
Oh how can I render to iterm colors? I've seen themer generate an i3.conf and Xdefaults file but iTerm2 can't import either of those files.

If I want `themer` to create a colorscheme using a certain plugin, how can I use that plugin when running `themer generate`? Do I manually edit `themer` (or a specific `__init__.py` file) to import and use my plugin?

**Comment by s-ol** [comment]
the last two steps of your OP take care of rendering to iTerm colors.

The parser is only there to load _from_ iTerm colors (parsing iTerm color files).

**Comment by Amar1729** [comment]
Ah I see, that makes more sense. 
However, there's another slight issue - the iTerm colorscheme definition is a bit different from Xdefaults or i3. For some reason they use a layout that individually specifies the RGB components of each ansi color, like this:  
```
<key>Ansi 3 Color</key>
<dict>
	<key>Alpha Component</key>
	<real>1</real>
	<key>Blue Component</key>
	<real>0.12941177189350128</real>
	<key>Color Space</key>
	<string>Calibrated</string>
	<key>Green Component</key>
	<real>0.60000002384185791</real>
	<key>Red Component</key>
	<real>0.84313726425170898</real>
</dict>
```

So I can't just place `{{red}}` in the `tpl` like other formats: instead, I have done `{{red0}}` for the red part of ansi color 0, and likewise for the 15 colors and foreground/background. Because of this different layout, do I instead modify the Jinja2 layout scheme by adding appropriate keys for it to replace?

**Comment by s-ol** [comment]
I see, that is exactly the problem I discussed in #40. I just pushed a new branch `filters`, can you try using it like `{{ color | red | float}}`?

**Comment by Amar1729** [comment]
Sure I'll try. However this repo still only lists 2 branches (develop and master)?

**Comment by s-ol** [comment]
whoops, I had cloned it wrongly and pushed it to a local repo instead of github. it is up now.

**Comment by Amar1729** [comment]
Thanks for clarifying this for me. I was confused about plugins vs the templates that `themer` generates colors from.
