### ISSUE TITLE
Clearify how config.yaml works

### ISSUE THREAD

**Issue by Kaligule** [s-ol/themer#47]
This file is almost undocumented. Especially interesting would be:

- What values are allowed? Can I add a variable of any name if I want?
- Which values are required? Can I remove any variable I don't care fore (eg "transparency")
- If I generate a theme from a picture, what variables are set?
- If I dont specify a template underr "files:" but it exists in the file system, will it be rendered to a default or just be ignored? What happens if it is specified but does not exist?

**Comment by s-ol** [comment]
noted, for now the answers are:
- any / yes
- whichever you are using in your templates
- see [`ColorParser`](https://github.com/s-ol/themer/blob/develop/themer/__init__.py#L37), the values are the names. In addition three colors are aliased to `primary`, `secondary` and `tertiary`
- will be ignored / will error
