### ISSUE TITLE
wallfix.py doesn't set wallpaper

### ISSUE THREAD

**Issue by Kaligule** [s-ol/themer#50]
This might be a mistake on my site but it looks to me like `wallfix.py` creates and crops wallpapers, but doesn't activate them. Am I supposed to have an extra activator for that? Then why does it log "Setting wallpaper"?

**Comment by s-ol** [comment]
`wallfix.py` could be extended to activate the background image but all ways I know to do that are platform specific and/or require specific tools to be installed. The log is wrong, I think when this was in coleifers version it did set it.

Personally, I have my i3 set up to set the wallpaper on (re-)start so the i3Activator does this for me; this is again a case of 'confusing example/default configuration'.

**Comment by Kaligule** [comment]
I see. Should we perhaps have a big ammount of activators shipped by default for people who can't write their own? Since they are pretty easy to write (good job by the way) I could contribute 2 or 3. Or is it intended that there are so few in the repo, so people learn how to write them?

**Comment by s-ol** [comment]
@Kaligule not a lot of thought has gone into that, and I just never made any that i didn't use - more are definetely welcome.

I was also thinking to maybe support absolute paths in the activators array that are executed as subprocess hooks (so you can add shell scripts).

**Comment by Kaligule** [comment]
I will try to add some soon.

Shell scripts might be usefull (e.g. the i3activator is basically a online-shellscript). I don't think this would make impossible things possible though, just easier.
