### ISSUE TITLE
Do you have a logo?

### ISSUE THREAD

**Issue by ghost** [s-ol/themer#57]
I'm an aspiring Graphic Designer, and student in programming and Information Technology. I want to give back to the industry by participating in Open Source Projects. 

I will create a logo and any other graphic that you might need, and most likely help with the coding when I'm skilled enough. 
Thanks.

**Comment by s-ol** [comment]
hey, of course I would much appreciate a contribution like that! There isn't currently a logo or anything similar.

Good luck & enjoy yourself on your quests in programming and open source :)

**Comment by ghost** [comment]
Hey, @s-ol  this is what I came up with for now. I would do some simplifying then I would send you the final via email. 
![image](https://user-images.githubusercontent.com/26881067/27770433-be431ddc-5f0c-11e7-82f5-31c1bc93a3c2.png)

**Comment by lizzieab** [comment]
hi there @jervlapsley , looking round for easy issues I thought I could fix and saw your logo, I think maybe it might be worth continuing the black border around the bottom? Might make it look a little more complete, and could then potentially be used as a web app icon without the text below? I love the idea though!

**Comment by s-ol** [comment]
yes, it would be great to have it independent of the text so it can be used at various sizes more readily. for this reason i think it would also be good to have a little less details around the whole icon and to have the boxes more aligned and spaces of consistent size to reduce visual noise.

**Comment by ghost** [comment]
Thanks for the feed-back guys. I lost all my work due to a power surge damaging my hard drive, so I'd have to re-make it.

**Comment by s-ol** [comment]
@jervlapsley: oh, that sucks :/
if you feel like it I would of course still appreciate a logo design and display it in the README etc, but it's also by no means necessary and frankly I'm currently not up for building a better documentation site that would do a proper logo justice.
