### ISSUE TITLE
No such file or directory: '/usr/share/themer/default'

### ISSUE THREAD

**Issue by olofsjod** [s-ol/themer#64]
Hi,

I tried to install themer via pip and are receiving `No such file or directory: '/usr/share/themer/default'` whenever I try to start it. I am noting that there is no such thing as a `/usr/share/themer/` on my computer. 

Is this a bug or is it a feature? I am running the latest version of Fedora 26.

**Comment by s-ol** [comment]
This has been fixed in #62 / 305598e8e22f85456dfa4ef9d3f8c171e3d754d4; just needs a push to PyPi still.

**Comment by s-ol** [comment]
Sorry for the delay, 1.8.3 is live now.
